### ISSUE TITLE
Could not find boost headers in include search path

### ISSUE THREAD

**Issue by yangchunhe** [JacketWoo/mongosync#1]
[root@svr mongosync]# make
scons -C ./dep/mongo-cxx-driver --ssl install -j 8
scons: Entering directory `/root/mongosync/mongosync/dep/mongo-cxx-driver'
scons: Reading SConscript files ...
Mkdir("build/scons")
scons version: 2.5.1
python version: 2 6 6 'final' 0
Checking whether the C++ compiler works... yes
Checking whether the C compiler works... yes
Checking if C++ compiler "g++" is GCC... yes
Checking if C compiler "gcc" is GCC... yes
Checking if C compiler supports -Wno-unused-local-typedefs... no
Checking if C compiler supports -Wno-unused-function... yes
Checking if C compiler supports -Wno-unused-private-field... no
Checking if C compiler supports -Wno-deprecated-declarations... yes
Checking if C compiler supports -Wno-tautological-constant-out-of-range-compare... no
Checking if C compiler supports -Wno-unused-const-variable... no
Checking if C compiler supports -Wno-missing-braces... yes
Checking if we are using libstdc++... yes
Checking for libstdc++ 4.6.0 or better... no
Checking if we are on a POSIX system... yes
Checking if the POSIX monotonic clock is supported... yes
Checking for __thread... yes
Checking for gcc __atomic builtins... no
Checking for useable __sync builtins... yes
Checking for C++ header file boost/version.hpp... no
Could not find boost headers in include search path
make: *** [dep/mongo-cxx-driver/build/install/lib/libmongoclient.a] Error 1

**Comment by yangchunhe** [comment]
make 不了

**Comment by gaodq** [comment]
需要安装boost库

**Comment by kingjike** [comment]
centos下：
yum install boost boost-devel

cd mongosync/dep/mongo-cxx-driver/build/scons/sconf_temp/
vi conftest_17.cpp
将文件内容：#include "boost/version.hpp"
替换为：#include "/usr/include/boost/version.hpp"

然后在重新编译就可以了

**Comment by elipoke** [comment]
g++ -o build/linux2/ssl/mongo/base/global_initializer.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -DMONGO_HAVE___THREAD -DBOOST_THREAD_USES_DATETIME -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_POSIX_MONOTONIC_CLOCK -DMONGO_HAVE_TIMEGM -DLIBMONGOCLIENT_BUILDING -DSTATIC_LIBMONGOCLIENT -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Isrc/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Isrc -Ibuild/linux2/ssl/mongo -Isrc/mongo src/mongo/base/global_initializer.cpp
g++ -o build/linux2/ssl/mongo/bson/util/bson_extract.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -DMONGO_HAVE___THREAD -DBOOST_THREAD_USES_DATETIME -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_POSIX_MONOTONIC_CLOCK -DMONGO_HAVE_TIMEGM -DLIBMONGOCLIENT_BUILDING -DSTATIC_LIBMONGOCLIENT -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Isrc/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Isrc -Ibuild/linux2/ssl/mongo -Isrc/mongo src/mongo/bson/util/bson_extract.cpp
g++ -o build/linux2/ssl/mongo/client/bulk_operation_builder.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -DMONGO_HAVE___THREAD -DBOOST_THREAD_USES_DATETIME -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_POSIX_MONOTONIC_CLOCK -DMONGO_HAVE_TIMEGM -DLIBMONGOCLIENT_BUILDING -DSTATIC_LIBMONGOCLIENT -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Isrc/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Isrc -Ibuild/linux2/ssl/mongo -Isrc/mongo src/mongo/client/bulk_operation_builder.cpp
g++ -o build/linux2/ssl/mongo/client/bulk_update_builder.o -c -Wnon-virtual-dtor -Woverloaded-virtual -fPIC -ggdb -pthread -Wall -Wsign-compare -Wno-unknown-pragmas -Winvalid-pch -pipe -Werror -O3 -Wno-unused-local-typedefs -Wno-unused-function -Wno-deprecated-declarations -Wno-missing-braces -DMONGO_EXPOSE_MACROS -D_FILE_OFFSET_BITS=64 -DMONGO_HAVE___THREAD -DBOOST_THREAD_USES_DATETIME -DMONGO_HAVE_HEADER_UNISTD_H -DMONGO_HAVE_POSIX_MONOTONIC_CLOCK -DMONGO_HAVE_TIMEGM -DLIBMONGOCLIENT_BUILDING -DSTATIC_LIBMONGOCLIENT -Ibuild/linux2/ssl/third_party/gtest-1.7.0/include -Isrc/third_party/gtest-1.7.0/include -Ibuild/linux2/ssl -Isrc -Ibuild/linux2/ssl/mongo -Isrc/mongo src/mongo/client/bulk_update_builder.cpp
src/mongo/base/global_initializer.cpp:32:18: error: 'mongo::{anonymous}::_theGlobalInitializer' defined but not used [-Werror=unused-variable]
     Initializer* _theGlobalInitializer = &getGlobalInitializer();
                  ^
cc1plus: all warnings being treated as errors
scons: *** [build/linux2/ssl/mongo/base/global_initializer.o] Error 1
scons: building terminated because of errors.
Makefile:58: recipe for target 'dep/mongo-cxx-driver/build/install/lib/libmongoclient.a' failed
make: *** [dep/mongo-cxx-driver/build/install/lib/libmongoclient.a] Error 2

**Comment by gaodq** [comment]
#3
